#!/usr/bin/env bash
# gen_config_h.sh - emit agent/include/config.h from listener UI values.
# Usage:
#   extender/tools/gen_config_h.sh URL KEYHEX [SLEEPMS] [WATERMARK]
# Example:
#   ./extender/tools/gen_config_h.sh \
#       http://127.0.0.1:8080/api/v1/status \
#       2114d9fc4faa8d7149000a9063d19c4d \
#       10000

set -euo pipefail

if [ $# -lt 2 ]; then
  echo "usage: $0 URL KEYHEX [SLEEPMS] [WATERMARK]" >&2
  exit 1
fi

URL="$1"
KEY="$2"
SLEEP_MS="${3:-10000}"
WATERMARK="${4:-a04a4178}"

if ! [[ "$KEY" =~ ^[0-9a-fA-F]{32}$ ]]; then
  echo "ERR: key must be 32 hex chars" >&2
  exit 1
fi
if ! [[ "$WATERMARK" =~ ^[0-9a-fA-F]{8}$ ]]; then
  echo "ERR: watermark must be 8 hex chars" >&2
  exit 1
fi
if ! [[ "$SLEEP_MS" =~ ^[0-9]+$ ]]; then
  echo "ERR: SLEEPMS must be a positive integer" >&2
  exit 1
fi

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
NONAMEAX_ROOT="${NONAMEAX_ROOT:-$( cd "$SCRIPT_DIR/../.." && pwd )}"
OUT="$NONAMEAX_ROOT/agent/include/config.h"

cat > "$OUT" <<EOF
#ifndef NAX_CONFIG_H
#define NAX_CONFIG_H

/* NoNameAx implant compile-time configuration.
 * Generated by extender/tools/gen_config_h.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ). */

#define NAX_CALLBACK_URL      "$URL"
#define NAX_ENCRYPT_KEY_HEX   "$KEY"
#define NAX_SLEEP_MS          ${SLEEP_MS}u
#define NAX_WATERMARK_HEX     "$WATERMARK"

#endif /* NAX_CONFIG_H */
EOF

echo "wrote $OUT"
